# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Circle_Factory(object):
    def setupUi(self, Circle_Factory):
        Circle_Factory.setObjectName("Circle_Factory")
        Circle_Factory.resize(600, 600)
        self.ImButton = QtWidgets.QPushButton(Circle_Factory)
        self.ImButton.setGeometry(QtCore.QRect(190, 230, 211, 71))
        self.ImButton.setObjectName("ImButton")

        self.retranslateUi(Circle_Factory)
        QtCore.QMetaObject.connectSlotsByName(Circle_Factory)

    def retranslateUi(self, Circle_Factory):
        _translate = QtCore.QCoreApplication.translate
        Circle_Factory.setWindowTitle(_translate("Circle_Factory", "Circle_Factory"))
        self.ImButton.setText(_translate("Circle_Factory", "я кнопка кстати"))
